### ISSUE TITLE
Test takes a very long time to return result

### ISSUE THREAD

**Issue by hoboris** [valentinilk/compose-shimmer#10] opened 2022-09-21 18:47 UTC
Hey Valentin! I'm implementing unit tests for my Composables that use your shimmer, but they are not passing within a reasonable time. When `Modifier.shimmer()` is called, unit tests seems to continue running for a while, then eventually finishes after a very long time. 

Given the following Activity:

```
class ShimmerActivity : AppCompatActivity()  {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .shimmer()
                    .background(Color.White)
            )
        }
    }
}
```

And the following test :

```
@RunWith(RobolectricTestRunner::class)
class ShimmerActivityTest {

    @Test
    fun shimmer_activity_test() {
        launchActivity<ShimmerActivity>().onActivity {
            assertTrue(true)
        }
    }
}
```

The test only passes after more than 2 hours.

![image](https://user-images.githubusercontent.com/12737725/191584384-ff5fa8d0-0166-440a-b5a5-65f83d4c8294.png)

But when `//.shimmer()` is commented out, then the test passes  as expected after a few seconds.

![image](https://user-images.githubusercontent.com/12737725/191584520-77117a21-3c43-4515-b76b-e5c42488a110.png)

**Comment by valentinilk** [comment] 2022-10-04 10:16
Hey @hoboris, this is probably caused by the `LaunchedEffect` that is hidden inside the shimmer modifier.

I'm not familiar with Robolectric, but could get it to work by disabling the automatic clock synchronization between the tests and compose UI ([Jetpack Documentation - Disable Autosync](https://developer.android.com/jetpack/compose/testing#disable-autosync)).

```
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import androidx.test.core.app.launchActivity
import org.junit.Rule
import org.robolectric.annotation.LooperMode

@RunWith(RobolectricTestRunner::class)
class MainActivityTest {

    @get:Rule
    val composeTestRule = createAndroidComposeRule<MainActivity>()

    @Test
    @LooperMode(LooperMode.Mode.PAUSED)
    fun testShimmer() {
        composeTestRule.mainClock.autoAdvance = false
        launchActivity<MainActivity>().onActivity {
            assert(true)
        }
    }
}
```

I'm not sure if that is the way to go with Robolectric, but I hope it helps. Let me know if I can close this issue. :)

**Closed** 2023-03-29 07:42 UTC
