### ISSUE TITLE
Demo app not compile!

### ISSUE THREAD

**Issue by Monabr** [valentinilk/compose-shimmer#17] opened 2023-05-29 20:49 UTC
`Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'ossrhUsername' for project ':shimmer' of type org.gradle.api.Project.`

**Comment by valentinilk** [comment] 2023-07-11 09:18
That's a duplicate of https://github.com/valentinilk/compose-shimmer/issues/13#issue-1644779683 

So that's the solution:
> Removing the whole afterEvaluate block in shimmer/build.gradle.kts should fix it. That is only required if you want to publish the build to maven.

**Closed by valentinilk** 2023-07-11 09:18 UTC
